export const SET_CAR_DATA = 'SET_CAR_DATA'
export const SET_ENGINE = 'SET_ENGINE'
export const SET_COLOR = 'SET_COLOR'
export const SET_WHEELS = 'SET_WHEELS'
export const RESET_SELECTION = 'RESET_SELECTION'
